//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockEx.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LockEx.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stark Bewölkt ähnelt.
        /// </summary>
        public static string BrokenClouds {
            get {
                return ResourceManager.GetString("BrokenClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klar ähnelt.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berlin ähnelt.
        /// </summary>
        public static string DefaultCity {
            get {
                return ResourceManager.GetString("DefaultCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 24 ähnelt.
        /// </summary>
        public static string DefaultHourFormat {
            get {
                return ResourceManager.GetString("DefaultHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        public static string DefaultLongTextMode {
            get {
                return ResourceManager.GetString("DefaultLongTextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die true ähnelt.
        /// </summary>
        public static string DefaultSecondsVisible {
            get {
                return ResourceManager.GetString("DefaultSecondsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        public static string DefaultTempSuffix {
            get {
                return ResourceManager.GetString("DefaultTempSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die leicht Bewölkt ähnelt.
        /// </summary>
        public static string FewClouds {
            get {
                return ResourceManager.GetString("FewClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In einer Woche ähnelt.
        /// </summary>
        public static string InAWeek {
            get {
                return ResourceManager.GetString("InAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In %d Tagen ähnelt.
        /// </summary>
        public static string InNDays {
            get {
                return ResourceManager.GetString("InNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten ähnelt.
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nebel ähnelt.
        /// </summary>
        public static string Mist {
            get {
                return ResourceManager.GetString("Mist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de ähnelt.
        /// </summary>
        public static string OWMlang {
            get {
                return ResourceManager.GetString("OWMlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regen ähnelt.
        /// </summary>
        public static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-DE ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewölkt ähnelt.
        /// </summary>
        public static string ScatteredClouds {
            get {
                return ResourceManager.GetString("ScatteredClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wetter anzeigen für ähnelt.
        /// </summary>
        public static string SettingCity {
            get {
                return ResourceManager.GetString("SettingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekunden anzeigen ähnelt.
        /// </summary>
        public static string SettingDisplaySeconds {
            get {
                return ResourceManager.GetString("SettingDisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12-Stunden Format ähnelt.
        /// </summary>
        public static string SettingHourFormat {
            get {
                return ResourceManager.GetString("SettingHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als Sperrbildschirm ähnelt.
        /// </summary>
        public static string SettingLockscreen {
            get {
                return ResourceManager.GetString("SettingLockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Langer-Text Modus ähnelt.
        /// </summary>
        public static string SettingLongTextMode {
            get {
                return ResourceManager.GetString("SettingLongTextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als Hintergrund ähnelt.
        /// </summary>
        public static string SettingsBackground {
            get {
                return ResourceManager.GetString("SettingsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperatur anzeigen in ähnelt.
        /// </summary>
        public static string SettingTempSuffix {
            get {
                return ResourceManager.GetString("SettingTempSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EINSTELLUNGEN ähnelt.
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die starker Regen ähnelt.
        /// </summary>
        public static string ShowerRain {
            get {
                return ResourceManager.GetString("ShowerRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schnee ähnelt.
        /// </summary>
        public static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  von  ähnelt.
        /// </summary>
        public static string SongBy {
            get {
                return ResourceManager.GetString("SongBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis ähnelt.
        /// </summary>
        public static string TempTo {
            get {
                return ResourceManager.GetString("TempTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übermorgen ähnelt.
        /// </summary>
        public static string TheDayAfter {
            get {
                return ResourceManager.GetString("TheDayAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewitter ähnelt.
        /// </summary>
        public static string Thunderstorm {
            get {
                return ResourceManager.GetString("Thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heute ähnelt.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morgen ähnelt.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entsperren ähnelt.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wetter in  ähnelt.
        /// </summary>
        public static string WeatherIn {
            get {
                return ResourceManager.GetString("WeatherIn", resourceCulture);
            }
        }
    }
}
